Repository bytzcurrency/BYTZ, pull requests merged in 2021-07, with the labels that each got.

#1 Setup for snapcraft building
  snap/local/patches/X001-default_data_dir.patch
  snap/snapcraft.yaml
Labels: build

#4 Update test_runner to run tokens in main check and det. mns in extended
  test/functional/test_runner.py
Labels: test

#3 New circleci configuration
  .circleci/config.yml
  contrib/devtools/git-subtree-check.sh
  contrib/devtools/lint-whitespace.sh
  depends/funcs.mk
Labels: build, test

#5 Set snapcraft to build from master
  snap/snapcraft.yaml
Labels: build

#7 Updated README.md
  README.md
Labels: documentation

#8 [GUI] Update unlock for staking interface
  src/qt/askpassphrasedialog.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletview.cpp
  src/qt/walletview.h
  src/wallet/rpcwallet.cpp
Labels: enhancement
